title: "<span style='color: black;'>Pedro Scala</span>"
logo: "<img src='/profile_pic.jpg' alt='Profile Pic' style='width: 300px;'/>"
description: "<span style='font-size: larger;'>Data Analyst</span>"
show_downloads: false
theme: jekyll-theme-minimal
