title: "<span style='color: black;'>Pedro Scala</span>"
logo:  /profile_pic.jpg
description: >
  <b><span style='font-size: larger;'>Data Analyst</span></b><br />
  
I'm a dedicated Data Analyst with a background in Chemical Engineering and an MBA in Data Science & Analytics. With over four years of experience, 
I've worked with data in various-sized companies. My data analysis journey started during scientific research, emphasizing the importance of computing.
Living in Toronto for a year broadened my business perspective. Currently, I'm a Financial Data Analyst in the beverage industry. 
I'm a curious individual, always seeking new challenges to exercise my analytical skills. My interests include Data Analytics, Data Science, Statistics, Machine Learning, Visualization, SQL, Python, Spark, R, and Power BI.
I'm constantly improving my skills for challenging projects.

show_downloads: false
theme: jekyll-theme-minimal
